### ISSUE TITLE
Assertion failed.  Abort (core dumped)

### ISSUE THREAD

**Issue by gsullivan** [yTakatsukasa/vcd_hierarchy_manipulator#2]
I get the following error messages when I run the script:

vcd_hier_manip my.vcd
vcd_hier_manip: vcd_header.cpp:389: vcd_module::vcd_module(string_view&, const string_view&, vcd_module*): Assertion `signals.find(sig->get_name()) == signals.end()' failed.
Abort (core dumped)

This is some info about my OS:

file vcd_hier_manip
vcd_hier_manip: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=d1ccb93a2b3405c2aa1b67f719316f91ab197412, not stripped

Here is the VCD file (header only):

[vcd.txt](https://github.com/yTakatsukasa/vcd_hierarchy_manipulator/files/7017407/vcd.txt)

**Comment by yTakatsukasa** [comment]
Thanks for the report.
It takes some time for me to remember the code. I will get back to you.

**Comment by yTakatsukasa** [comment]
I expect #3 fixes the issue.


This program is written long time ago when C++11 is not necessarily available on pure CentOS.
It's awkward to see my old immature code, but I don't have bandwidth to rewrite everything.

BTW the latest SystemC looks to be able to make VCD with hierarchy by setting environment variable `SC_VCD_SCOPES=ENABLE`.
https://github.com/accellera-official/systemc/blob/604182509559ae42c34e878f508bae7c18abbbd6/src/sysc/tracing/sc_vcd_trace.cpp#L1808
